### ISSUE TITLE
Supprimer la GeometryType non fonctionnelle : Square

### ISSUE THREAD

**Issue by Bloumy** [IGNF/ol-geometry-editor#10]
On pouvait utiliser jusqu'à présent geometryType: Square, or elle n'est pas fonctionnelle, ni référencée dans la doc, et n'a jamais eu d'utilisations jusqu'à présent.

**Comment by mborne** [comment]
L'idée de base était de permettre la saisie de bbox. C'est utilisé dans la version GpU pour les fiches de métadonnées de mémoire.

**Comment by Bloumy** [comment]
Square faisait doublon avec Rectangle ici les deux étaient des "GeometryType" distincts (sauf que "Square" n'avait pas été maintenu correctement avec les évolutions du code et n'avait jamais été utilisé).
Je vais donc le supprimer quitte à le refaire de zero dans un futur où on en aurait besoin.
