### ISSUE TITLE
Lien exemple Get started Readme

### ISSUE THREAD

**Issue by vinsag** [IGNF/ol-geometry-editor#7]
Le lien dans la partie Get Started renvoie vers une erreur 404 :
See example/geometry-types.html

**Comment by nviel** [comment]
Tant que tu y es Alexis, pourrais-tu corriger la faute d'orthographe dans la description:

`.. qui peut être formaté en texte et édit**é** à l'aide d'une carte.`

;-P

**Comment by Bloumy** [comment]
Readme corrigé ! Merci pour le coup d'oeil Nicolas !
